# Docs: https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
registries:
    nuget-public:
        type: nuget-feed
        url: https://api.nuget.org/v3/index.json

    docker-public:
        type: docker-registry
        url: https://index.docker.io/v1/

    npm-public:
        type: npm-registry
        url: https://registry.npmjs.org/

updates:
  - package-ecosystem: dotnet-sdk
    directory: /src/
    schedule:
      interval: monthly
    groups:
      backward-compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /src/
    registries:
      - nuget-artifactory
    schedule:
      interval: monthly
    groups:
      backward-compatible-updates:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    registries:
      - docker-artifactory
    schedule:
      interval: monthly
