services:

# Application Dependencies
    mssql:
        build: ./mssql
        environment:
            SA_PASSWORD: "P@ssword123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "1443:1433"
        container_name: ExampleSql
        hostname: mssql

    redis:
        image: redis:latest
        ports:
            - "1379:6379"
        container_name: ExampleRedisCache

# Development Resources
    mailhog:
        # build: ./mailhog
        image: mailhog/mailhog:latest
        logging:
            driver: 'none' # Disable logging
        ports:
            - "1021:1025" # smtp server
            - "8021:8025" # web ui
        container_name: ExampleMailhog

    otel-collector:
        image: datalust/seq:latest
        environment:
            ACCEPT_EULA: "Y"
            SEQ_API_KEY: "1234567890"
        ports:
            - "4341:80" # OpenTelemetry
        container_name: ExampleOtelCollector