services:

# Development Resources

    mssql:
        build: ./mssql
        environment:
            SA_PASSWORD: "P@ssword123!"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"
        ports:
            - "4110:1433" # SQL Server, Update port if needed
        container_name: EduSiProjectSql
        hostname: mssql
