// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Startup.Data.Models.Db.dboSchema;


namespace Startup.Data.Models.Db.dboSchema;

public partial class AgencyToMediaContent
{
    public Guid AgencyId { get; set; }

    public Guid MediaContentId { get; set; }

    public virtual Agency Agency { get; set; }

    public virtual MediaContent MediaContent { get; set; }
}