// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Startup.Data.Models.Db.dboSchema;


namespace Startup.Data.Models.Db.dboSchema;

public partial class Agency
{
    public Guid Id { get; set; }

    public string CompanyName { get; set; }

    public string CompanyLogoUrl { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string StateOrProvince { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public bool IsEnabled { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? WebAppEulaacceptDate { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual ICollection<AgencyToMediaContent> AgencyToMediaContents { get; set; } = new List<AgencyToMediaContent>();

    public virtual ICollection<UserToAgency> UserToAgencies { get; set; } = new List<UserToAgency>();
}