// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Startup.Data.Models.Db.dboSchema;


namespace Startup.Data.Models.Db.dboSchema;

public partial class AuthenticationLog
{
    public Guid Id { get; set; }

    public string AspNetUsersId { get; set; }

    public short AuthStatusId { get; set; }

    public string Username { get; set; }

    public DateTime LogDate { get; set; }

    public virtual AspNetUser AspNetUsers { get; set; }

    public virtual AuthenticationStatus AuthStatus { get; set; }
}