// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Startup.Data.Models.Db.dboSchema;


namespace Startup.Data.Models.Db.dboSchema;

public partial class MediaContent
{
    public Guid Id { get; set; }

    public string FileName { get; set; }

    public string FileNameExt { get; set; }

    public string TempFilePath { get; set; }

    public string DownloadFileUrl { get; set; }

    public string BlobFileNamePath { get; set; }

    public string FileSignature { get; set; }

    public long FileSize { get; set; }

    public int? PlayLength { get; set; }

    public bool IsEnabled { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime DateCreated { get; set; }

    public DateTime LastUpdated { get; set; }

    public virtual ICollection<AgencyToMediaContent> AgencyToMediaContents { get; set; } = new List<AgencyToMediaContent>();
}