# For more info on HTTP files go to https://aka.ms/vs/httpfile

# User Login
POST https://localhost:7100/api/Auth/Login
Content-Type: application/json

{
  "username": "Michael@AGameEmpowerment.com",
  "password": "P@ssword123",
  "displayName": "Michael"
}

