# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST https://localhost:7100/api/v1.0/Randomize/GenerateRandomPairList
Content-Type: application/json

[
  "Name 1",
  "Name 2",
  "Name 3",
  "Name 4",
  "Name 5",
  "Name 6",
  "Name 7",
  "Name 8"
]

###

POST https://localhost:7100/api/v1.0/Randomize/GenerateRandomPairList
Content-Type: application/json

[
  "Name 1",
  "Name 2",
  "Name 3",
  "Name 4",
  "Name 5",
  "Name 6",
  "Name 7",
  "Name 8",
  "Name 9"
]
