/*
Deployment script for StartupExample

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;

GO

CREATE DATABASE [StartupExample]
GO

USE [StartupExample];


GO
PRINT N'Creating Table [dbo].[Agency]...';


GO
CREATE TABLE [dbo].[Agency] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [CompanyName]          NVARCHAR (250)   NOT NULL,
    [CompanyLogoURL]       VARCHAR (250)    NOT NULL,
    [Address1]             NVARCHAR (100)   NULL,
    [Address2]             NVARCHAR (100)   NULL,
    [City]                 NVARCHAR (100)   NULL,
    [StateOrProvince]      NVARCHAR (50)    NULL,
    [PostalCode]           NVARCHAR (20)    NULL,
    [Country]              NVARCHAR (100)   NULL,
    [IsEnabled]            BIT              NOT NULL,
    [IsDeleted]            BIT              NOT NULL,
    [WebAppEULAAcceptDate] DATETIME2 (7)    NULL,
    [DateCreated]          DATETIME2 (7)    NOT NULL,
    [LastUpdated]          DATETIME2 (7)    NOT NULL,
    CONSTRAINT [PK_Agency] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[Agency].[IX_Agency_CompanyName]...';


GO
CREATE NONCLUSTERED INDEX [IX_Agency_CompanyName]
    ON [dbo].[Agency]([CompanyName] ASC);


GO
PRINT N'Creating Table [dbo].[AgencyToMediaContent]...';


GO
CREATE TABLE [dbo].[AgencyToMediaContent] (
    [AgencyId]       UNIQUEIDENTIFIER NOT NULL,
    [MediaContentId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_AgencyToMediaContent] PRIMARY KEY CLUSTERED ([AgencyId] ASC, [MediaContentId] ASC)
);


GO
PRINT N'Creating Table [dbo].[AspNetRoleClaims]...';


GO
CREATE TABLE [dbo].[AspNetRoleClaims] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [RoleId]     NVARCHAR (450) NOT NULL,
    [ClaimType]  NVARCHAR (MAX) NULL,
    [ClaimValue] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetRoleClaims].[IX_AspNetRoleClaims_RoleId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AspNetRoleClaims_RoleId]
    ON [dbo].[AspNetRoleClaims]([RoleId] ASC);


GO
PRINT N'Creating Table [dbo].[AspNetRoles]...';


GO
CREATE TABLE [dbo].[AspNetRoles] (
    [Id]               NVARCHAR (450) NOT NULL,
    [Name]             NVARCHAR (256) NULL,
    [NormalizedName]   NVARCHAR (256) NULL,
    [ConcurrencyStamp] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetRoles].[RoleNameIndex]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex]
    ON [dbo].[AspNetRoles]([NormalizedName] ASC) WHERE ([NormalizedName] IS NOT NULL);


GO
PRINT N'Creating Table [dbo].[AspNetUserClaims]...';


GO
CREATE TABLE [dbo].[AspNetUserClaims] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [UserId]     NVARCHAR (450) NOT NULL,
    [ClaimType]  NVARCHAR (MAX) NULL,
    [ClaimValue] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetUserClaims].[IX_AspNetUserClaims_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AspNetUserClaims_UserId]
    ON [dbo].[AspNetUserClaims]([UserId] ASC);


GO
PRINT N'Creating Table [dbo].[AspNetUserLogins]...';


GO
CREATE TABLE [dbo].[AspNetUserLogins] (
    [LoginProvider]       NVARCHAR (128) NOT NULL,
    [ProviderKey]         NVARCHAR (128) NOT NULL,
    [ProviderDisplayName] NVARCHAR (MAX) NULL,
    [UserId]              NVARCHAR (450) NOT NULL,
    CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY CLUSTERED ([LoginProvider] ASC, [ProviderKey] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetUserLogins].[IX_AspNetUserLogins_UserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AspNetUserLogins_UserId]
    ON [dbo].[AspNetUserLogins]([UserId] ASC);


GO
PRINT N'Creating Table [dbo].[AspNetUserRoles]...';


GO
CREATE TABLE [dbo].[AspNetUserRoles] (
    [UserId] NVARCHAR (450) NOT NULL,
    [RoleId] NVARCHAR (450) NOT NULL,
    CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY CLUSTERED ([UserId] ASC, [RoleId] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetUserRoles].[IX_AspNetUserRoles_RoleId]...';


GO
CREATE NONCLUSTERED INDEX [IX_AspNetUserRoles_RoleId]
    ON [dbo].[AspNetUserRoles]([RoleId] ASC);


GO
PRINT N'Creating Table [dbo].[AspNetUsers]...';


GO
CREATE TABLE [dbo].[AspNetUsers] (
    [Id]                   NVARCHAR (450)     NOT NULL,
    [UserName]             NVARCHAR (256)     NULL,
    [NormalizedUserName]   NVARCHAR (256)     NULL,
    [Email]                NVARCHAR (256)     NULL,
    [NormalizedEmail]      NVARCHAR (256)     NULL,
    [EmailConfirmed]       BIT                NOT NULL,
    [PasswordHash]         NVARCHAR (MAX)     NULL,
    [SecurityStamp]        NVARCHAR (MAX)     NULL,
    [ConcurrencyStamp]     NVARCHAR (MAX)     NULL,
    [PhoneNumber]          NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed] BIT                NOT NULL,
    [TwoFactorEnabled]     BIT                NOT NULL,
    [LockoutEnd]           DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]       BIT                NOT NULL,
    [AccessFailedCount]    INT                NOT NULL,
    CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[AspNetUsers].[EmailIndex]...';


GO
CREATE NONCLUSTERED INDEX [EmailIndex]
    ON [dbo].[AspNetUsers]([NormalizedEmail] ASC);


GO
PRINT N'Creating Index [dbo].[AspNetUsers].[UserNameIndex]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex]
    ON [dbo].[AspNetUsers]([NormalizedUserName] ASC) WHERE ([NormalizedUserName] IS NOT NULL);


GO
PRINT N'Creating Table [dbo].[AspNetUserTokens]...';


GO
CREATE TABLE [dbo].[AspNetUserTokens] (
    [UserId]        NVARCHAR (450) NOT NULL,
    [LoginProvider] NVARCHAR (128) NOT NULL,
    [Name]          NVARCHAR (128) NOT NULL,
    [Value]         NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED ([UserId] ASC, [LoginProvider] ASC, [Name] ASC)
);


GO
PRINT N'Creating Table [dbo].[AuthenticationLog]...';


GO
CREATE TABLE [dbo].[AuthenticationLog] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [AspNetUsersId] NVARCHAR (450)   NULL,
    [AuthStatusId]  SMALLINT         NOT NULL,
    [Username]      NVARCHAR (200)   NOT NULL,
    [LogDate]       DATETIME2 (7)    NOT NULL,
    CONSTRAINT [PK_AuthenticationLog] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[AuthenticationStatus]...';


GO
CREATE TABLE [dbo].[AuthenticationStatus] (
    [Id]          SMALLINT      NOT NULL,
    [Name]        VARCHAR (20)  NOT NULL,
    [Description] VARCHAR (200) NOT NULL,
    CONSTRAINT [PK_AuthenticationStatus] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[MediaContent]...';


GO
CREATE TABLE [dbo].[MediaContent] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [FileName]         NVARCHAR (250)   NOT NULL,
    [FileNameExt]      NVARCHAR (50)    NOT NULL,
    [TempFilePath]     VARCHAR (512)    NULL,
    [DownloadFileUrl]  VARCHAR (1024)   NULL,
    [BlobFileNamePath] VARCHAR (1024)   NULL,
    [FileSignature]    VARCHAR (512)    NOT NULL,
    [FileSize]         BIGINT           NOT NULL,
    [PlayLength]       INT              NULL,
    [IsEnabled]        BIT              NOT NULL,
    [IsDeleted]        BIT              NOT NULL,
    [DateCreated]      DATETIME2 (7)    NOT NULL,
    [LastUpdated]      DATETIME2 (7)    NOT NULL,
    CONSTRAINT [PK_MediaContent] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Index [dbo].[MediaContent].[IX_MediaContent_DateCreated]...';


GO
CREATE NONCLUSTERED INDEX [IX_MediaContent_DateCreated]
    ON [dbo].[MediaContent]([DateCreated] ASC);


GO
PRINT N'Creating Index [dbo].[MediaContent].[IX_MediaContent_FileName]...';


GO
CREATE NONCLUSTERED INDEX [IX_MediaContent_FileName]
    ON [dbo].[MediaContent]([FileName] ASC);


GO
PRINT N'Creating Table [dbo].[UserToAgency]...';


GO
CREATE TABLE [dbo].[UserToAgency] (
    [UserId]   NVARCHAR (450)   NOT NULL,
    [AgencyId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_UserToAgency] PRIMARY KEY CLUSTERED ([UserId] ASC, [AgencyId] ASC)
);


GO
PRINT N'Creating Index [dbo].[UserToAgency].[IX_UserToAgency_AdvertiserId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UserToAgency_AdvertiserId]
    ON [dbo].[UserToAgency]([AgencyId] ASC);


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT (NewSequentialId()) FOR [Id];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT ('http://www.StartupExample.com/content/images/DefaultLogo.png') FOR [CompanyLogoURL];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT ((1)) FOR [IsEnabled];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT ((0)) FOR [IsDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT (GetUtcDate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[Agency]...';


GO
ALTER TABLE [dbo].[Agency]
    ADD DEFAULT (GetUtcDate()) FOR [LastUpdated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[AuthenticationLog]...';


GO
ALTER TABLE [dbo].[AuthenticationLog]
    ADD DEFAULT (NewSequentialId()) FOR [Id];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[AuthenticationLog]...';


GO
ALTER TABLE [dbo].[AuthenticationLog]
    ADD DEFAULT (GetUtcDate()) FOR [LogDate];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MediaContent]...';


GO
ALTER TABLE [dbo].[MediaContent]
    ADD DEFAULT (NewSequentialId()) FOR [Id];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MediaContent]...';


GO
ALTER TABLE [dbo].[MediaContent]
    ADD DEFAULT ((0)) FOR [IsEnabled];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MediaContent]...';


GO
ALTER TABLE [dbo].[MediaContent]
    ADD DEFAULT ((0)) FOR [IsDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MediaContent]...';


GO
ALTER TABLE [dbo].[MediaContent]
    ADD DEFAULT (GetUtcDate()) FOR [DateCreated];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[MediaContent]...';


GO
ALTER TABLE [dbo].[MediaContent]
    ADD DEFAULT (GetUtcDate()) FOR [LastUpdated];


GO
PRINT N'Creating Foreign Key [dbo].[FK_AgencyToMediaContent_Agency]...';


GO
ALTER TABLE [dbo].[AgencyToMediaContent] WITH NOCHECK
    ADD CONSTRAINT [FK_AgencyToMediaContent_Agency] FOREIGN KEY ([AgencyId]) REFERENCES [dbo].[Agency] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AgencyToMediaContent_MediaContent]...';


GO
ALTER TABLE [dbo].[AgencyToMediaContent] WITH NOCHECK
    ADD CONSTRAINT [FK_AgencyToMediaContent_MediaContent] FOREIGN KEY ([MediaContentId]) REFERENCES [dbo].[MediaContent] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetRoleClaims_AspNetRoles_RoleId]...';


GO
ALTER TABLE [dbo].[AspNetRoleClaims] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetUserClaims_AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserClaims] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetUserLogins_AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserLogins] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetUserRoles_AspNetRoles_RoleId]...';


GO
ALTER TABLE [dbo].[AspNetUserRoles] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[AspNetRoles] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetUserRoles_AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserRoles] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AspNetUserTokens_AspNetUsers_UserId]...';


GO
ALTER TABLE [dbo].[AspNetUserTokens] WITH NOCHECK
    ADD CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating Foreign Key [dbo].[FK_AuthenticationLog_AspNetUsers]...';


GO
ALTER TABLE [dbo].[AuthenticationLog] WITH NOCHECK
    ADD CONSTRAINT [FK_AuthenticationLog_AspNetUsers] FOREIGN KEY ([AspNetUsersId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AuthenticationLog_AuthenticationStatus]...';


GO
ALTER TABLE [dbo].[AuthenticationLog] WITH NOCHECK
    ADD CONSTRAINT [FK_AuthenticationLog_AuthenticationStatus] FOREIGN KEY ([AuthStatusId]) REFERENCES [dbo].[AuthenticationStatus] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserToAgency_Agency]...';


GO
ALTER TABLE [dbo].[UserToAgency] WITH NOCHECK
    ADD CONSTRAINT [FK_UserToAgency_Agency] FOREIGN KEY ([AgencyId]) REFERENCES [dbo].[Agency] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_UserToAgency_AspNetUsers]...';


GO
ALTER TABLE [dbo].[UserToAgency] WITH NOCHECK
    ADD CONSTRAINT [FK_UserToAgency_AspNetUsers] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AspNetUsers] ([Id]);


GO
/*
Post-Deployment Script Template
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.
 Use SQLCMD syntax to include a file in the post-deployment script.
 Example:      :r .\myfile.sql
 Use SQLCMD syntax to reference a variable in the post-deployment script.
 Example:      :setvar TableName MyTable
               SELECT * FROM [$(TableName)]
--------------------------------------------------------------------------------------
*/

DECLARE @AgencyId AS UNIQUEIDENTIFIER

SET @AgencyId = NewId()

/* Add system roles */

-- Agency SaaS administrator / Owner role
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyAdmin') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000000'
           ,'AgencyAdmin'
           ,'AGENCYADMIN'
           ,'02000000-0000-0000-0000-200000000000'
        )
    COMMIT TRAN
END
--GO

-- Agency role that designates the login as an employee of the agency
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyEmployee') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000100'
           ,'AgencyEmployee'
           ,'AGENCYEMPLOYEE'
           ,'02000000-0000-0000-0000-200000000100'
        )
    COMMIT TRAN
END
--GO

-- Agency role that manages the billing and upkeep for their account with StartupExample. Visibility into invoices with StartupExample.com
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyBilling') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000200'
           ,'AgencyBilling'
           ,'AGENCYBILLING'
           ,'02000000-0000-0000-0000-200000000200'
        )
    COMMIT TRAN
END
--GO

-- Agency role that manages customer / buisness accounts
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyAccountMgr') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000300'
           ,'AgencyAccountMgr'
           ,'AGENCYACCOUNTMGR'
           ,'02000000-0000-0000-0000-200000000300'
        )
    COMMIT TRAN
END
--GO

-- Agency role that manages the media production workflow
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyProductionMgr') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000400'
           ,'AgencyProductionMgr'
           ,'AGENCYPRODUCTIONMGR'
           ,'02000000-0000-0000-0000-200000000400'
        )
    COMMIT TRAN
END
--GO

-- Agency role that onboards new businesses and supports existing business to advertise with them
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencySalesRep') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000500'
           ,'AgencySalesRep'
           ,'AGENCYSALESREP'
           ,'02000000-0000-0000-0000-200000000500'
        )
    COMMIT TRAN
END
--GO

-- Agency role that allows visibility into reports
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyReports') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000600'
           ,'AgencyReports'
           ,'AGENCYREPORTS'
           ,'02000000-0000-0000-0000-200000000600'
        )
    COMMIT TRAN
END
--GO

-- Agency role that manages where advertisments are displayed or published and full player control
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyLocationMgr') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000700'
           ,'AgencyLocationMgr'
           ,'AGENCYLOCATIONMGR'
           ,'02000000-0000-0000-0000-200000000700'
        )
    COMMIT TRAN
END
--GO

-- Agency role that grants a non-employee visibility into their location's playlist and limited player functionality
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetRoles] WHERE [Name] = 'AgencyLocationViewer') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetRoles]
        (
           [Id]
           ,[Name]
           ,[NormalizedName]
           ,[ConcurrencyStamp]
        )
        VALUES
        (
           '20000000-0000-0000-0000-200000000800'
           ,'AgencyLocationViewer'
           ,'AGENCYLOCATIONVIEWER'
           ,'02000000-0000-0000-0000-200000000800'
        )
    COMMIT TRAN
END
--GO


/* Add the default internal Agency */

-- StartupExample Company
IF(SELECT COUNT(Id) AS Id FROM [dbo].[Agency] WHERE [CompanyName] = 'Agency') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO [dbo].[Agency] (
            [CompanyName]
            ,[Address1]
            ,[City]
            ,[StateOrProvince]
            ,[PostalCode]
            ,[Country]
            ,[WebAppEULAAcceptDate]
        )
        VALUES
        (
            'Agency'
            , '1234 Someplace St.'
            , 'Eagle Mountain'
            , 'Utah'
            , '84005'
            , 'United States'
            , GetUtcDate()
        )
    COMMIT TRAN
END
--GO

SELECT TOP 1 @AgencyId = [Id]
FROM [dbo].[Agency]
WHERE [CompanyName] = 'Agency'

/* Add a block of users with roles for default test accounts */

-- The Password hash = "P@ssword123"
-- Add user account
IF(SELECT COUNT(Id) AS Id FROM [dbo].[AspNetUsers] WHERE [UserName] = 'Michael@AGameEmpowerment.com') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetUsers]
        (
           [Id]
           ,[UserName]
           ,[NormalizedUserName]
           ,[Email]
           ,[NormalizedEmail]
           ,[EmailConfirmed]
           ,[PasswordHash]
           ,[SecurityStamp]
           ,[ConcurrencyStamp]
           ,[PhoneNumber]
           ,[PhoneNumberConfirmed]
           ,[TwoFactorEnabled]
           ,[LockoutEnd]
           ,[LockoutEnabled]
           ,[AccessFailedCount]
        )
        VALUES
        (
           '8458614f-e35b-4731-b01f-64d62f7c9368'
           ,'Michael@AGameEmpowerment.com'
           ,'MICHAEL@AGAMEEMPOWERMENT.COM'
           ,'Michael@AGameEmpowerment.com'
           ,'MICHAEL@AGAMEEMPOWERMENT.COM'
           , 1
           ,'AQAAAAEAACcQAAAAEF8KJcc/KJKDm4bkdsyzPMILI/TTG+OWP8vKRXNdEicIknrTddTHFfRJWEC+gNa5Mg=='
           ,'775HTQYXYVWQUHIAUVZRLPN6OS7VJXZB'
           ,'64e2108a-7018-42bd-a661-c01b0061585e'
           ,'12082011179'
           , 0
           , 0
           , NULL
           , 0
           , 0
        )
    COMMIT TRAN
END
--GO

-- Add user role to Michael@AGameEmpowerment.com
IF(SELECT COUNT(UserId) AS Id FROM [dbo].[AspNetUserRoles]
    WHERE [UserId] = '8458614f-e35b-4731-b01f-64d62f7c9368' and [RoleId] = '20000000-0000-0000-0000-200000000000') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AspNetUserRoles]
        (
           [UserId]
           ,[RoleId]
        )
        VALUES
        (
           '8458614f-e35b-4731-b01f-64d62f7c9368'
           ,'20000000-0000-0000-0000-200000000000'
        )
    COMMIT TRAN
END
--GO

-- Add relationship to default Agency
IF(SELECT COUNT(UserId) AS Id FROM [dbo].[UserToAgency]
    WHERE [UserId] = '8458614f-e35b-4731-b01f-64d62f7c9368' and [AgencyId] = @AgencyId) <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[UserToAgency]
        (
           [UserId]
           ,[AgencyId]
        )
        VALUES
        (
           '8458614f-e35b-4731-b01f-64d62f7c9368'
           ,@AgencyId
        )
    COMMIT TRAN
END
--GO

/* Authentication Status */

IF(SELECT COUNT(Id) AS Id FROM [dbo].[AuthenticationStatus] WHERE [Name] = 'Success') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AuthenticationStatus]
        (
            [Id]
           ,[Name]
           ,[Description]
        )
        VALUES
        (
           '1'
           ,'Success'
           ,'Successful login attempt'
        )
    COMMIT TRAN
END
--GO

IF(SELECT COUNT(Id) AS Id FROM [dbo].[AuthenticationStatus] WHERE [Name] = 'Failure') <= 0
BEGIN
    BEGIN TRAN
        INSERT INTO dbo.[AuthenticationStatus]
        (
            [Id]
           ,[Name]
           ,[Description]
        )
        VALUES
        (
           '2'
           ,'Failure'
           ,'Failure login attempt'
        )
    COMMIT TRAN
END
--GO

GO

USE tempdb
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [StartupExample];


GO
ALTER TABLE [dbo].[AgencyToMediaContent] WITH CHECK CHECK CONSTRAINT [FK_AgencyToMediaContent_Agency];

ALTER TABLE [dbo].[AgencyToMediaContent] WITH CHECK CHECK CONSTRAINT [FK_AgencyToMediaContent_MediaContent];

ALTER TABLE [dbo].[AspNetRoleClaims] WITH CHECK CHECK CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId];

ALTER TABLE [dbo].[AspNetUserClaims] WITH CHECK CHECK CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId];

ALTER TABLE [dbo].[AspNetUserLogins] WITH CHECK CHECK CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId];

ALTER TABLE [dbo].[AspNetUserRoles] WITH CHECK CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId];

ALTER TABLE [dbo].[AspNetUserRoles] WITH CHECK CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId];

ALTER TABLE [dbo].[AspNetUserTokens] WITH CHECK CHECK CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId];

ALTER TABLE [dbo].[AuthenticationLog] WITH CHECK CHECK CONSTRAINT [FK_AuthenticationLog_AspNetUsers];

ALTER TABLE [dbo].[AuthenticationLog] WITH CHECK CHECK CONSTRAINT [FK_AuthenticationLog_AuthenticationStatus];

ALTER TABLE [dbo].[UserToAgency] WITH CHECK CHECK CONSTRAINT [FK_UserToAgency_Agency];

ALTER TABLE [dbo].[UserToAgency] WITH CHECK CHECK CONSTRAINT [FK_UserToAgency_AspNetUsers];


GO
PRINT N'Update complete.';


GO
