// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Startup.Data.Models.Db;
using Startup.Data.Models.Db.dboSchema;

namespace Startup.Data.Repositories.Db;

public partial class StartupExampleContainer
{
    public StartupExampleContainer(DbContextOptions<StartupExampleContainer> options)
        : base(options)
    {
    }

    public virtual DbSet<Agency> Agencies { get; set; }

    public virtual DbSet<AgencyToMediaContent> AgencyToMediaContents { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }

    public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }

    public virtual DbSet<AuthenticationLog> AuthenticationLogs { get; set; }

    public virtual DbSet<AuthenticationStatus> AuthenticationStatuses { get; set; }

    public virtual DbSet<MediaContent> MediaContents { get; set; }

    public virtual DbSet<UserToAgency> UserToAgencies { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agency>(entity =>
        {
            entity.ToTable("Agency");

            entity.HasIndex(e => e.CompanyName, "IX_Agency_CompanyName");

            entity.Property(e => e.Id).HasDefaultValueSql("NewSequentialId()");
            entity.Property(e => e.Address1).HasMaxLength(100);
            entity.Property(e => e.Address2).HasMaxLength(100);
            entity.Property(e => e.City).HasMaxLength(100);
            entity.Property(e => e.CompanyLogoUrl)
                .IsRequired()
                .HasMaxLength(250)
                .IsUnicode(false)
                .HasDefaultValue("http://www.StartupExample.com/content/images/DefaultLogo.png")
                .HasColumnName("CompanyLogoURL");
            entity.Property(e => e.CompanyName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.DateCreated).HasDefaultValueSql("GetUtcDate()");
            entity.Property(e => e.IsEnabled).HasDefaultValue(true);
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("GetUtcDate()");
            entity.Property(e => e.PostalCode).HasMaxLength(20);
            entity.Property(e => e.StateOrProvince).HasMaxLength(50);
            entity.Property(e => e.WebAppEulaacceptDate).HasColumnName("WebAppEULAAcceptDate");
        });

        modelBuilder.Entity<AgencyToMediaContent>(entity =>
        {
            entity.HasKey(e => new { e.AgencyId, e.MediaContentId });

            entity.ToTable("AgencyToMediaContent");

            entity.HasOne(d => d.Agency).WithMany(p => p.AgencyToMediaContents)
                .HasForeignKey(d => d.AgencyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AgencyToMediaContent_Agency");

            entity.HasOne(d => d.MediaContent).WithMany(p => p.AgencyToMediaContents)
                .HasForeignKey(d => d.MediaContentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AgencyToMediaContent_MediaContent");
        });

        modelBuilder.Entity<AspNetRole>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetRoleClaim>(entity =>
        {
            entity.HasIndex(e => e.RoleId, "IX_AspNetRoleClaims_RoleId");

            entity.Property(e => e.RoleId).IsRequired();

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetRoleClaims).HasForeignKey(d => d.RoleId);
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUserClaim>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_AspNetUserClaims_UserId");

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserClaims).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserLogin>(entity =>
        {
            entity.HasKey(e => new { e.LoginProvider, e.ProviderKey });

            entity.HasIndex(e => e.UserId, "IX_AspNetUserLogins_UserId");

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.ProviderKey).HasMaxLength(128);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserLogins).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserRole>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.RoleId });

            entity.HasIndex(e => e.RoleId, "IX_AspNetUserRoles_RoleId");

            entity.HasOne(d => d.Role).WithMany(p => p.AspNetUserRoles).HasForeignKey(d => d.RoleId);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserRoles).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AspNetUserToken>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.LoginProvider, e.Name });

            entity.Property(e => e.LoginProvider).HasMaxLength(128);
            entity.Property(e => e.Name).HasMaxLength(128);

            entity.HasOne(d => d.User).WithMany(p => p.AspNetUserTokens).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<AuthenticationLog>(entity =>
        {
            entity.ToTable("AuthenticationLog");

            entity.Property(e => e.Id).HasDefaultValueSql("NewSequentialId()");
            entity.Property(e => e.AspNetUsersId).HasMaxLength(450);
            entity.Property(e => e.LogDate).HasDefaultValueSql("GetUtcDate()");
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.AspNetUsers).WithMany(p => p.AuthenticationLogs)
                .HasForeignKey(d => d.AspNetUsersId)
                .HasConstraintName("FK_AuthenticationLog_AspNetUsers");

            entity.HasOne(d => d.AuthStatus).WithMany(p => p.AuthenticationLogs)
                .HasForeignKey(d => d.AuthStatusId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuthenticationLog_AuthenticationStatus");
        });

        modelBuilder.Entity<AuthenticationStatus>(entity =>
        {
            entity.ToTable("AuthenticationStatus");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MediaContent>(entity =>
        {
            entity.ToTable("MediaContent");

            entity.HasIndex(e => e.DateCreated, "IX_MediaContent_DateCreated");

            entity.HasIndex(e => e.FileName, "IX_MediaContent_FileName");

            entity.Property(e => e.Id).HasDefaultValueSql("NewSequentialId()");
            entity.Property(e => e.BlobFileNamePath)
                .HasMaxLength(1024)
                .IsUnicode(false);
            entity.Property(e => e.DateCreated).HasDefaultValueSql("GetUtcDate()");
            entity.Property(e => e.DownloadFileUrl)
                .HasMaxLength(1024)
                .IsUnicode(false);
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(250);
            entity.Property(e => e.FileNameExt)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FileSignature)
                .IsRequired()
                .HasMaxLength(512)
                .IsUnicode(false);
            entity.Property(e => e.LastUpdated).HasDefaultValueSql("GetUtcDate()");
            entity.Property(e => e.TempFilePath)
                .HasMaxLength(512)
                .IsUnicode(false);
        });

        modelBuilder.Entity<UserToAgency>(entity =>
        {
            entity.HasKey(e => new { e.UserId, e.AgencyId });

            entity.ToTable("UserToAgency");

            entity.HasIndex(e => e.AgencyId, "IX_UserToAgency_AdvertiserId");

            entity.HasOne(d => d.Agency).WithMany(p => p.UserToAgencies)
                .HasForeignKey(d => d.AgencyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserToAgency_Agency");

            entity.HasOne(d => d.User).WithMany(p => p.UserToAgencies)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserToAgency_AspNetUsers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}